model_paths:
  llm: "path/to/llm/model"
  tts: "path/to/tts/model"
  
user_preferences:
  voice: "default_voice"
  language: "en-US"
  
avatar_settings:
  personality_traits:
    - "friendly"
    - "curious"
    - "playful"
  animation_speed: 1.0
  
voice_detection:
  cue_words:
    - "hello"
    - "help"
    - "avatar"
  
  # Enhanced VAD Configuration
  enhanced_vad:
    enabled: true
    vad_engine: "hybrid"  # pyannote, silero, hybrid
    mode: "lightweight"  # lightweight, balanced, high_accuracy
    fallback_to_basic: true
    
    # VAD Settings
    vad_model: "pyannote/segmentation-3.0"
    vad_onset_threshold: 0.5
    vad_offset_threshold: 0.5
    vad_min_duration_on: 0.1
    vad_min_duration_off: 0.1
    
    # Silero VAD Settings
    silero_threshold: 0.5
    silero_min_speech_duration_ms: 250
    silero_max_speech_duration_s: 30
    silero_min_silence_duration_ms: 100
    silero_window_size_samples: 1536
    
    # Diarization Settings
    enable_diarization: true
    diarization_model: "pyannote/speaker-diarization-3.1"
    min_speakers: 1
    max_speakers: 2
    speaker_verification_enabled: true
    
    # STT Settings  
    stt_model: "small"  # tiny, base, small, medium, large
    stt_language: "en"
    stt_device: "auto"  # auto, cpu, cuda
    stt_compute_type: "float16"  # float16, int8, float32
    stt_cpu_threads: 0
    
    # Audio Processing
    sample_rate: 16000
    chunk_duration: 1.0
    min_speech_duration: 0.5
    max_speech_duration: 30.0
    silence_threshold: 0.01
  
database:
  path: "path/to/database.db"
