ai:
  llm:
    enabled: true
    max_tokens: 2048
    memory_enabled: true
    model_name: TinyLlama-1.1B-Chat-v1.0.Q4_K_M.gguf
    model_path: /home/nyx/ai2d_chat/src/models/llm
    temperature: 0.7
audio:
  chunk_size: 1024
  enabled: true
  sample_rate: 16000
  stt:
    enabled: true
    language: auto
    model_path: /home/nyx/ai2d_chat/src/models/faster-whisper
    model_size: base
  tts:
    enabled: true
    model_path: /home/nyx/ai2d_chat/src/models/tts
    speed: 1.0
    voice: default
  vad:
    enabled: true
    model_path: /home/nyx/ai2d_chat/src/models/silero_vad
    threshold: 0.5
audio_processing:
  audio_input_path: /home/nyx/ai2d_chat/cache/audio_input
  audio_output_path: /home/nyx/ai2d_chat/cache/audio_output
database:
  conversations_db: /home/nyx/ai2d_chat/src/databases/conversations.db
  live2d_db: /home/nyx/ai2d_chat/src/databases/live2d.db
  paths:
    ai2d_chat: /home/nyx/ai2d_chat/src/databases/ai2d_chat.db
    conversations: /home/nyx/ai2d_chat/src/databases/conversations.db
    live2d_models: /home/nyx/ai2d_chat/src/databases/live2d.db
    personality: /home/nyx/ai2d_chat/src/databases/personality.db
    system: /home/nyx/ai2d_chat/src/databases/system.db
    user_profiles: /home/nyx/ai2d_chat/src/databases/user_profiles.db
    user_sessions: /home/nyx/ai2d_chat/src/databases/user_sessions.db
    users: /home/nyx/ai2d_chat/src/databases/users.db
  personality_db: /home/nyx/ai2d_chat/src/databases/personality.db
general:
  logging_file: /home/nyx/ai2d_chat/cache/logs/app.log
  secrets_file: /home/nyx/ai2d_chat/.secrets
integrated_models:
  llm:
    model_name: TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF
    model_path: /home/nyx/ai2d_chat/src/models/llm
  stt:
    model_path: /home/nyx/ai2d_chat/src/models/faster-whisper
    stt_model: large-v3
  tts:
    model_path: /home/nyx/ai2d_chat/src/models/tts/kokoro
    voice_path: /home/nyx/ai2d_chat/src/models/tts/voices
  vad:
    model_path: /home/nyx/ai2d_chat/src/models/silero_vad
live2d:
  auto_model_refresh: true
  default_model: null
  enabled: true
  integration_mode: embedded
  model_discovery_enabled: true
  models_directory: /home/nyx/ai2d_chat/src/live2d_models
  viewer_web_path: /home/nyx/ai2d_chat/live2d-viewer-web
live2d_models:
  Epsilon:
    model_info:
      path: /home/nyx/ai2d_chat/src/live2d_models/epsilon
  Haru:
    model_info:
      path: /home/nyx/ai2d_chat/src/live2d_models/haru
  Haruka:
    model_info:
      path: /home/nyx/ai2d_chat/src/live2d_models/haruka
  Iori:
    model_info:
      path: /home/nyx/ai2d_chat/src/live2d_models/iori
  Mori:
    model_info:
      path: /home/nyx/ai2d_chat/src/live2d_models/mori
  Nodoka:
    model_info:
      path: /home/nyx/ai2d_chat/src/live2d_models/nodoka
  Tsumiki:
    model_info:
      path: /home/nyx/ai2d_chat/src/live2d_models/tsumiki
  hiyori:
    model_info:
      path: /home/nyx/ai2d_chat/src/live2d_models/hiyori
  kanade:
    model_info:
      path: /home/nyx/ai2d_chat/src/live2d_models/kanade
logging:
  directory: /home/nyx/ai2d_chat/cache/logs
  file_log_path: /home/nyx/ai2d_chat/cache/logs/app.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_files: 10
paths:
  cache_dir: /home/nyx/ai2d_chat/cache
  config_dir: /home/nyx/ai2d_chat
  data_dir: /home/nyx/ai2d_chat
  database_dir: /home/nyx/ai2d_chat/src/databases
  live2d_models_dir: /home/nyx/ai2d_chat/src/live2d_models
  models_dir: /home/nyx/ai2d_chat/src/models
server:
  cors_enabled: true
  debug: true
  dev_port: 19081
  host: 127.0.0.1
  port: 19080
service:
  deployment_mode: pipx
  environment_vars:
    PYTHONPATH: /home/nyx/ai2d_chat
    ai2d_chat_CONFIG: /home/nyx/ai2d_chat/config.yaml
  working_directory: /home/nyx/ai2d_chat
